services:
    # nginx    
    router:
        build:
            dockerfile: Dockerfile
            target: router                  
        ports:
            - "80:80"
    # php
    php-server:
        build:
            dockerfile: ./php/Dockerfile
            target: php-server
        environment:
            LOGGLY_TOKEN: "${LOGGLY_TOKEN}"
            MYSQL_HOST: "${MYSQL_HOST}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        extra_hosts:
            - host.docker.internal:host-gateway
    # mysql
    mysql-database:
        image: mysql:latest
        volumes:
            - mysqldata:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d            
        restart: always                    
        command: --init-file /docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_HOST: "${MYSQL_HOST}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            
volumes:
    mysqldata: