# Generated by Selenium IDE
import pytest
import time
import json
import os
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from dotenv import load_dotenv
load_dotenv()

class TestSQLInjectionFailedLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.host_url = os.getenv("TEST_HOST")
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    base_url = os.environ.get('TEST_HOST', 'default_url_if_not_set')
    self.driver.get("https://" + base_url + "/login.php")
    self.driver.set_window_size(1008, 1080)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("barf")
    self.driver.find_element(By.ID, "password").send_keys("\' OR 1 = 1; -- ")
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()    
    elements = self.driver.find_elements(By.LINK_TEXT, "Welcome barf")
    assert len(elements) == 0
  
