# Generated by Selenium IDE
import pytest
import time
import json
import os
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from dotenv import load_dotenv
load_dotenv()

class TestProperLogin():
  
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}    
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_properLogin(self):
    base_url = os.environ.get('TEST_BASE_URL', 'default_url_if_not_set')
    self.driver.get("https://" + base_url + "/login.php")
    self.driver.find_element(By.ID, "username").send_keys("bob_johnson")
    self.driver.find_element(By.ID, "password").send_keys("Johnson1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.find_element(By.LINK_TEXT, "Welcome bob_johnson").text == "Welcome bob_johnson"
  
