# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from dotenv import load_dotenv
load_dotenv()

base_url = os.environ.get('TEST_BASE_URL')

class TestHttps():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_https(self):
    self.driver.get("https://" + base_url + "/login.php")
    self.driver.set_window_size(1183, 1184)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".text-center:nth-child(1)")
    assert len(elements) > 0
  
