# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUnlimitedloginattempts():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_unlimitedloginattempts(self):
    self.driver.get("https://localhost/login.php")
    self.driver.find_element(By.ID, "username").send_keys("barf")
    self.driver.find_element(By.ID, "password").send_keys("barf")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "username").send_keys("barf")
    self.driver.find_element(By.ID, "password").send_keys("barf")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "username").send_keys("barf")
    self.driver.find_element(By.ID, "password").send_keys("barf")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".alert")
    assert len(elements) == 0
  
